# This runs on the Docker Host
# add to rc.local:
# docker-compose -d -f /etc/docker-compose.yml up
# This is for the development environment on xw6600
# Container version is 'latest'

version: '3'

services:
  forecaster-service:
    container_name: forecaster-service
    image: registry:5000/forecaster-service:$version
    logging:
      driver: syslog
    environment:
      STAGE: $stage
    ports:
      - "9501:9501"
